name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3️⃣ Build JAR
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # 4️⃣ Login to Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
           -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 5️⃣ Build Docker Image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/crickers-app .

    # 6️⃣ Push Image
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/crickers-app

    # 7️⃣ Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/crickers-app
          docker stop crickers-container || true
          docker rm crickers-container || true
          docker run -d -p 8080:8080 \
            --name crickers-container \
            --restart unless-stopped \
            ${{ secrets.DOCKER_USERNAME }}/crickers-app
