name: CI/CD Spring Boot Docker EC2

on:
  push:
    branches:
      - master
      - Test

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1ï¸âƒ£ Checkout code
    - name: Checkout
      uses: actions/checkout@v4

    # 2ï¸âƒ£ Setup Java
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # ğŸ—ï¸ 3ï¸âƒ£ Build + Test
    - name: Build & Test with Maven
      run: mvn clean verify

    # ğŸ” 4ï¸âƒ£ Docker Hub Login
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ğŸ³ 5ï¸âƒ£ Build Docker Image
    - name: Build Image
      run: docker build -t seegisangu/myapp:latest .

    # ğŸ“¦ 6ï¸âƒ£ Push Image
    - name: Push Image
      run: docker push seegisangu/myapp:latest

    # ğŸš€ 7ï¸âƒ£ Deploy to EC2
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |

          echo "Branch: ${{ github.ref_name }}"

          # Stop & remove old container
          docker stop myapp-container || true
          docker rm myapp-container || true

          # Pull latest image
          docker pull seegisangu/myapp:latest

          # Run container
          docker run -d -p 8080:8080 \
            --name myapp-container \
            --restart always \
            --add-host=host.docker.internal:host-gateway \
            seegisangu/myapp:latest
